### ISSUE TITLE
Why can't the data set address be found

### ISSUE THREAD

**Issue by myl666666** [FatemehAskari/Enhancing-Few-Shot-Classification-through-Learnable-Multi-Scale-Embedding-and-Attention-Mechanisms#3]
Hello, I am very interested in your work, but I need the following questions when loading the data set, how is your data set set here
[problem.txt](https://github.com/user-attachments/files/17945378/problem.txt)

**Comment by FatemehAskari** [comment]
I apologize for my late response. You have two options to set up the Easy Few-Shot Learning code:

Clone the code using the link https://github.com/sicara/easy-few-shot-learning.git, and then in the easyfsl/datasets folder, change the line MINI_IMAGENET_SPECS_DIR = Path("data/mini_imagenet") to the location where you have placed your dataset. Just make sure to import this file in train.py.
The second option, which I don't recommend, is to place your dataset in the same directory where you are running the code. This way, you won't need to modify the Easy Few-Shot Learning code.
If you have any other questions, feel free to ask!

**Comment by FatemehAskari** [comment]
> Hello, I am very interested in your work, but I need the following questions when loading the data set, how is your data set set here [problem.txt](https://github.com/user-attachments/files/17945378/problem.txt)

I apologize for my late response. You have two options to set up the Easy Few-Shot Learning code:

Clone the code using the link https://github.com/sicara/easy-few-shot-learning.git, and then in the easyfsl/datasets folder, change the line MINI_IMAGENET_SPECS_DIR = Path("data/mini_imagenet") to the location where you have placed your dataset. Just make sure to import this file in train.py.
The second option, which I don't recommend, is to place your dataset in the same directory where you are running the code. This way, you won't need to modify the Easy Few-Shot Learning code.
If you have any other questions, feel free to ask!
